export * from './domanda-edit/domanda-edit.component';
export * from './step-anagrafica/step-anagrafica.component';
export * from './step-corsi-di-formazione/step-corsi-di-formazione.component';
export * from './step-dichiarazoini/step-dichiarazoini.component';
export * from './step-qualifica-professionale/step-qualifica-professionale.component';
export * from './step-qualifica-sede/step-qualifica-sede.component';
export * from './step-titoli-di-studio/step-titoli-di-studio.component';
export * from './step-corsi-di-formazione/aggiungi-corsi/aggiungi-corsi.component';
export * from './step-titoli-di-studio/aggiungi-dati/aggiungi-dati.component';
